apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: nginx              # must match labels on target pods.
  ports:
  - port: 80                # Port exposed by the serivce
    targetPort: 80          # Port on the Pod to forward traffic to.



# to run this kubectl apply -f simple-service.yaml
# check: kubectl get service myservice.
# 🧠 Note:
# This is a ClusterIP service by default (only accessible within the cluster).
# If you want it to be accessible outside the cluster, use type: NodePort or LoadBalancer.
