apiVersion: apps/v1      # kubernetes API version for the resource, apps/v1 is used for deployments
kind: Deployment          # tells kubernetes, what kind of object this is - in this case, a Deployment,, A Deployment manages a set of Pods and ensures they are running and updated.
metadata:
  name: system-deployment      # this is the name of deployment object, youll use this to refer to it later.
  labels:
    app: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      - name: system
        image: system:1.0-SNAPSHOT
        ports:
        - containerPort: 4000 # change if your app uses a different port
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: system-service
spec:
  type: NodePort
  selector:
    app: system
  ports:
    - protocol: TCP
      port: 80    # the port your clients will access.
      targetPort: 4000  # the port your app is running on inside the container.
      nodePort: 30080  # fixed external port(accessible via localhost:30080).
      
      
